# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('merchant_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_product_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('short_product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('product_image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('buy_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, db_column='SKU', max_length=64, null=True)),
                ('product_type', models.CharField(blank=True, max_length=128, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=128, null=True)),
                ('style', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.CharField(blank=True, max_length=128, null=True)),
                ('material', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=55, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
