# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:02
from __future__ import unicode_literals

from django.db import migrations


from product_api.models import Network, Merchant

def add_network(apps, schema_editor):
    Network.objects.create(network_name = 'RAN', status = True)

def add_merchants(apps, schema_editor):
    RAN = Network.objects.get(id = 1)
    Merchant.objects.create(external_merchant_id = 36145, merchant_name = "7 For All Mankind, a division of DG Premium Brands, LLC", network = RAN)
    Merchant.objects.create(external_merchant_id = 41754, merchant_name = "AG Jeans", network = RAN)
    Merchant.objects.create(external_merchant_id = 37615, merchant_name = "AHAlife.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 40742, merchant_name = "Aerosoles", network = RAN)
    Merchant.objects.create(external_merchant_id = 42156, merchant_name = "Ann Taylor", network = RAN)
    Merchant.objects.create(external_merchant_id = 35300, merchant_name = "Bergdorf Goodman (Neiman Marcus)", network = RAN)
    Merchant.objects.create(external_merchant_id = 13867, merchant_name = "Bloomingdale''s", network = RAN)
    Merchant.objects.create(external_merchant_id = 41890, merchant_name = "CAMI", network = RAN)
    Merchant.objects.create(external_merchant_id = 37811, merchant_name = "Club Monaco", network = RAN)
    Merchant.objects.create(external_merchant_id = 41563, merchant_name = "DolceVita.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 37152, merchant_name = "Dorothy Perkins(US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 39270, merchant_name = "Dune (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 41730, merchant_name = "Frame Denim", network = RAN)
    Merchant.objects.create(external_merchant_id = 39876, merchant_name = "Frank And Oak", network = RAN)
    Merchant.objects.create(external_merchant_id = 25004, merchant_name = "Horchow.com (Neiman Marcus),", network = RAN)
    Merchant.objects.create(external_merchant_id = 41132, merchant_name = "Italist.com US", network = RAN)
    Merchant.objects.create(external_merchant_id = 39476, merchant_name = "James Perse Enterprises", network = RAN)
    Merchant.objects.create(external_merchant_id = 40464, merchant_name = "Jenny Bird", network = RAN)
    Merchant.objects.create(external_merchant_id = 24797, merchant_name = "Karen Millen Fashions Limited", network = RAN)
    Merchant.objects.create(external_merchant_id = 42157, merchant_name = "LOFT", network = RAN)
    Merchant.objects.create(external_merchant_id = 42445, merchant_name = "Lauren Moshi", network = RAN)
    Merchant.objects.create(external_merchant_id = 40480, merchant_name = "Lord & Taylor", network = RAN)
    Merchant.objects.create(external_merchant_id = 38014, merchant_name = "Luisa via Roma (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 3184, merchant_name = "Macys.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 42447, merchant_name = "Michael Lauren", network = RAN)
    Merchant.objects.create(external_merchant_id = 40776, merchant_name = "Mother Denim", network = RAN)
    Merchant.objects.create(external_merchant_id = 25003, merchant_name = "Neiman Marcus", network = RAN)
    Merchant.objects.create(external_merchant_id = 36025, merchant_name = "Neiman Marcus Last Call (Neiman Marcus)", network = RAN)
    Merchant.objects.create(external_merchant_id = 38464, merchant_name = "New York & Company", network = RAN)
    Merchant.objects.create(external_merchant_id = 37793, merchant_name = "Oasap Limited", network = RAN)
    Merchant.objects.create(external_merchant_id = 41846, merchant_name = "REVOLVE", network = RAN)
    Merchant.objects.create(external_merchant_id = 24274, merchant_name = "Rakuten Affiliate Network UK", network = RAN)
    Merchant.objects.create(external_merchant_id = 560, merchant_name = "Rakuten Affiliate Network Welcome Program", network = RAN)
    Merchant.objects.create(external_merchant_id = 40090, merchant_name = "Reformation", network = RAN)
    Merchant.objects.create(external_merchant_id = 38434, merchant_name = "River Island - US", network = RAN)
    Merchant.objects.create(external_merchant_id = 13816, merchant_name = "Saks Fifth Avenue", network = RAN)
    Merchant.objects.create(external_merchant_id = 38801, merchant_name = "Saks Fifth Avenue OFF 5TH", network = RAN)
    Merchant.objects.create(external_merchant_id = 39006, merchant_name = "Scotch & Soda (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 38193, merchant_name = "Sole Society", network = RAN)
    Merchant.objects.create(external_merchant_id = 41558, merchant_name = "Spring", network = RAN)
    Merchant.objects.create(external_merchant_id = 40914, merchant_name = "Target", network = RAN)
    Merchant.objects.create(external_merchant_id = 35861, merchant_name = "Topshop  US", network = RAN)
    Merchant.objects.create(external_merchant_id = 40462, merchant_name = "UNIQLO USA", network = RAN)
    Merchant.objects.create(external_merchant_id = 40830, merchant_name = "Veronica Beard", network = RAN)
    Merchant.objects.create(external_merchant_id = 38192, merchant_name = "Wildfox Couture US", network = RAN)


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_auto_20171108_0533'),
    ]

    operations = [
        migrations.RunPython(add_network),
        migrations.RunPython(add_merchants)
    ]
