# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:02
from __future__ import unicode_literals

from django.db import migrations


from product_api.models import Network, Merchant

def add_network(apps, schema_editor):
    Network.objects.create(name = 'RAN', active = 1)

def add_merchants(apps, schema_editor):
    RAN = Network.objects.get(id = 1)
    Merchant.objects.create(external_merchant_id = 36145, name = "7 For All Mankind, a division of DG Premium Brands, LLC", network = RAN)
    Merchant.objects.create(external_merchant_id = 41754, name = "AG Jeans", network = RAN)
    Merchant.objects.create(external_merchant_id = 37615, name = "AHAlife.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 40742, name = "Aerosoles", network = RAN)
    Merchant.objects.create(external_merchant_id = 42156, name = "Ann Taylor", network = RAN)
    Merchant.objects.create(external_merchant_id = 35300, name = "Bergdorf Goodman (Neiman Marcus)", network = RAN)
    Merchant.objects.create(external_merchant_id = 13867, name = "Bloomingdale''s", network = RAN)
    Merchant.objects.create(external_merchant_id = 41890, name = "CAMI", network = RAN)
    Merchant.objects.create(external_merchant_id = 37811, name = "Club Monaco", network = RAN)
    Merchant.objects.create(external_merchant_id = 41563, name = "DolceVita.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 37152, name = "Dorothy Perkins(US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 39270, name = "Dune (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 41730, name = "Frame Denim", network = RAN)
    Merchant.objects.create(external_merchant_id = 39876, name = "Frank And Oak", network = RAN)
    Merchant.objects.create(external_merchant_id = 25004, name = "Horchow.com (Neiman Marcus),", network = RAN)
    Merchant.objects.create(external_merchant_id = 41132, name = "Italist.com US", network = RAN)
    Merchant.objects.create(external_merchant_id = 39476, name = "James Perse Enterprises", network = RAN)
    Merchant.objects.create(external_merchant_id = 40464, name = "Jenny Bird", network = RAN)
    Merchant.objects.create(external_merchant_id = 24797, name = "Karen Millen Fashions Limited", network = RAN)
    Merchant.objects.create(external_merchant_id = 42157, name = "LOFT", network = RAN)
    Merchant.objects.create(external_merchant_id = 42445, name = "Lauren Moshi", network = RAN)
    Merchant.objects.create(external_merchant_id = 40480, name = "Lord & Taylor", network = RAN)
    Merchant.objects.create(external_merchant_id = 38014, name = "Luisa via Roma (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 3184, name = "Macys.com", network = RAN)
    Merchant.objects.create(external_merchant_id = 42447, name = "Michael Lauren", network = RAN)
    Merchant.objects.create(external_merchant_id = 40776, name = "Mother Denim", network = RAN)
    Merchant.objects.create(external_merchant_id = 25003, name = "Neiman Marcus", network = RAN)
    Merchant.objects.create(external_merchant_id = 36025, name = "Neiman Marcus Last Call (Neiman Marcus)", network = RAN)
    Merchant.objects.create(external_merchant_id = 38464, name = "New York & Company", network = RAN)
    Merchant.objects.create(external_merchant_id = 37793, name = "Oasap Limited", network = RAN)
    Merchant.objects.create(external_merchant_id = 41846, name = "REVOLVE", network = RAN)
    Merchant.objects.create(external_merchant_id = 24274, name = "Rakuten Affiliate Network UK", network = RAN)
    Merchant.objects.create(external_merchant_id = 560, name = "Rakuten Affiliate Network Welcome Program", network = RAN)
    Merchant.objects.create(external_merchant_id = 40090, name = "Reformation", network = RAN)
    Merchant.objects.create(external_merchant_id = 38434, name = "River Island - US", network = RAN)
    Merchant.objects.create(external_merchant_id = 13816, name = "Saks Fifth Avenue", network = RAN)
    Merchant.objects.create(external_merchant_id = 38801, name = "Saks Fifth Avenue OFF 5TH", network = RAN)
    Merchant.objects.create(external_merchant_id = 39006, name = "Scotch & Soda (US)", network = RAN)
    Merchant.objects.create(external_merchant_id = 38193, name = "Sole Society", network = RAN)
    Merchant.objects.create(external_merchant_id = 41558, name = "Spring", network = RAN)
    Merchant.objects.create(external_merchant_id = 40914, name = "Target", network = RAN)
    Merchant.objects.create(external_merchant_id = 35861, name = "Topshop  US", network = RAN)
    Merchant.objects.create(external_merchant_id = 40462, name = "UNIQLO USA", network = RAN)
    Merchant.objects.create(external_merchant_id = 40830, name = "Veronica Beard", network = RAN)
    Merchant.objects.create(external_merchant_id = 38192, name = "Wildfox Couture US", network = RAN)


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_auto_20171109_0740'),
    ]

    operations = [
        migrations.RunPython(add_network),
        migrations.RunPython(add_merchants)
    ]
