# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0010_product_availablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
