# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0012_colormap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantcategory',
            options={'verbose_name_plural': 'Merchant Categories'},
        ),
    ]
