# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0012_colormap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantcategory',
            options={'verbose_name_plural': 'Merchant Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='allume_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
