# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0013_auto_20180102_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allume_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
