# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0014_auto_20180103_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availablity',
            new_name='availability',
        ),
    ]
