# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0014_product_allume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcategory',
            name='allume_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
