# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0015_merchantcategory_allume_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_cat1', models.CharField(blank=True, max_length=128, null=True)),
                ('external_cat2', models.CharField(blank=True, max_length=128, null=True)),
                ('allume_cat1', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
