# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0015_auto_20180103_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merchant_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
