# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0016_categorymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='external_cat1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='external_cat2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
