# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0019_categorymap_allume_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymap',
            name='allume_cat1',
        ),
    ]
