# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0021_remove_merchantcategory_allume_name'),
        ('product_api', '0013_auto_20171220_2302'),
    ]

    operations = [
    ]
