# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0016_auto_20180103_1907'),
        ('product_api', '0022_merge_20180103_2148'),
    ]

    operations = [
    ]
