# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0023_merge_20180103_2222'),
        ('product_api', '0013_auto_20180105_2020'),
    ]

    operations = [
    ]
