# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0024_merge_20180115_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymap',
            name='pending_review',
            field=models.BooleanField(default=False),
        ),
    ]
