# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0025_product_raw_product_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('product_id', 'merchant_id')]),
        ),
    ]
