# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 18:46
from __future__ import unicode_literals

from django.db import migrations
import sqlparse

class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0026_auto_20180125_1743'),
    ]

    sql = "ALTER TABLE product_api_product CONVERT TO CHARACTER SET utf8;"

    operations = [
        migrations.RunSQL(sqlparse.split(sql)),
    ]
