# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0025_categorymap_pending_review'),
        ('product_api', '0026_auto_20180125_1743'),
    ]

    operations = [
    ]
