# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0027_merge_20180126_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymap',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
