# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0028_categorymap_merchant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='external_cat1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='external_cat2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
