# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0029_auto_20180212_2002'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allumecategory',
            index=models.Index(fields=['name'], name='product_api_name_037784_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['name'], name='product_api_name_9444c8_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymap',
            index=models.Index(fields=['external_cat1'], name='product_api_externa_c8b541_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymap',
            index=models.Index(fields=['external_cat2'], name='product_api_externa_b82c00_idx'),
        ),
    ]
