# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0031_auto_20180221_1724'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['allume_category'], name='product_api_allume__23e58b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant_id'], name='product_api_merchan_a8f549_idx'),
        ),
    ]
