# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0034_sizetermsmap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeTermsMap',
            new_name='SizeTermMap',
        ),
    ]
