# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0032_auto_20180302_2259'),
        ('product_api', '0035_auto_20180227_2247'),
    ]

    operations = [
    ]
