# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0037_auto_20180323_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='allumecategory',
            name='position',
            field=models.IntegerField(default=100),
        ),
    ]
