# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0038_auto_20180326_2347'),
        ('product_api', '0038_auto_20180328_1732'),
    ]

    operations = [
    ]
