# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0041_auto_20180403_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherTermMap',
        ),
    ]
