# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0042_auto_20180406_0023'),
        ('product_api', '0042_auto_20180409_2046'),
    ]

    operations = [
    ]
