# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0044_auto_20180412_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymap',
            options={'ordering': ['id']},
        ),
    ]
