# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0045_auto_20180424_1958'),
    ]

    operations = [
        #migrations.AlterUniqueTogether(
        #    name='categorymap',
        #    unique_together=set([('external_cat1', 'external_cat2')]),
        #),
    ]
