# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0047_auto_20180502_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='has_size_data',
            field=models.BooleanField(default=True),
        ),
    ]
