# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0048_auto_20180613_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='has_size_data',
        ),
    ]
