# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0051_auto_20180925_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_api.Network'),
        ),
    ]
