# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0052_auto_20180929_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='final_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='never_used_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tips',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twotap_feed_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twotap_usage_timeout_in_hours',
            field=models.IntegerField(default=1000000),
        ),
    ]
