version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      - elk
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3336:3306
    #volumes:
      #- ./allume_product_feeds.sql:/docker-entrypoint-initdb.d/allume_product_feeds.sql
      #- ./create_allume_products_table.sql:/docker-entrypoint-initdb.d/create_allume_products_table.sql
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/mysql-connector-java-5.1.43-bin.jar:/usr/share/logstash/mysql-connector-java-5.1.43-bin.jar
    links:
      - elasticsearch
      - mysql
    networks:
      - elk

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge