fields:
    - product_id
    - product_name
    - SKU
    - primary_category
    - secondary_category
    - product_url
    - product_image_url
    - buy_url
    - short_product_description
    - long_product_description
    - discount
    - discount_type
    - sale_price
    - retail_price
    - begin_date
    - end_date
    - brand
    - shipping
    - keywords
    - manufacturer_part_number
    - manufacturer_name
    - shipping_information
    - availability
    - universal_product_code
    - class_ID
    - currency
    - M1
    - pixel
    - attribute_1_misc
    - attribute_8_age
    - attribute_5_color
    - attribute_4_material
    - attribute_2_product_type
    - attribute_3_size
    - attribute_7_style
    - attribute_6_gender
    - attribute_9
    - attribute_10
    - modification
tiered_assignment_fields:
    secondary_category:
        - "parse_other_terms(datum['product_name'], kwargs['synonym_other_category_mapping'])"
        - "datum['secondary_category']"
        - "parse_category_from_product_name(datum['product_name'], kwargs['synonym_category_mapping'])"
