DROP TABLE IF EXISTS allume_client_360_temp;

CREATE TABLE IF NOT EXISTS allume_client_360_temp (
  ID                  INT       NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  wp_user_id          INT,
  first_name          TEXT,
  last_name           TEXT,
  address_1           TEXT,
  address_2           TEXT,
  city                TEXT,
  state               TEXT,
  country             TEXT,
  birthday            TEXT,
  occupation          TEXT,
  wear_to_work        TEXT,
  spend_free_time     TEXT,
  where_live          TEXT,
  time_of_day_text    TEXT,
  social_media        TEXT,
  instagram           TEXT,
  pinterest           TEXT,
  linkedin            TEXT,
  photo               TEXT,
  winter              TEXT,
  spring              TEXT,
  summer              TEXT,
  fall                TEXT,
  styling_count       INTEGER,
  last_styling_date   DATETIME,
  order_count         INTEGER,
  last_order_amt      DECIMAL,
  last_order_date     DATETIME,
  avg_items           DECIMAL,
  avg_amt             DECIMAL,
  heart_count         INTEGER,
  comment_count       INTEGER,
  star_count          INTEGER,
  signup_date         DATETIME,
  utm_source          TEXT,
  utm_campaign        TEXT,
  utm_term            TEXT,
  utm_medium          TEXT,
  referral_site       TEXT,
  hear_about_allume   TEXT,
  height              TEXT,
  weight              TEXT,
  bra_size            TEXT,
  body_part_attention TEXT,
  body_part_conceal   TEXT,
  fit_challenges      TEXT,
  hair_complex_color  TEXT,
  first_session_focus TEXT,
  looks_goal          TEXT,
  pieces_focus        TEXT,
  outfits_preference  TEXT,
  other_goals         TEXT,
  stores              TEXT,
  brands              TEXT,
  spending_tops       TEXT,
  spending_bottoms    TEXT,
  spending_dresses    TEXT,
  spending_jackets    TEXT,
  spending_shoes      TEXT,
  style_celebs        TEXT,
  style_looks         TEXT,
  style_jeans         TEXT,
  style_tops          TEXT,
  style_dress         TEXT,
  style_jacket        TEXT,
  style_shoe          TEXT,
  colors_preference   TEXT,
  style_avoid         TEXT,
  size_pants          TEXT,
  size_jeans          TEXT,
  size_tops           TEXT,
  size_shoe           TEXT,
  ears_pierced        TEXT,
  jewelry_style       TEXT,
  jewelry_type        TEXT,
  last_updated        TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
)
  ENGINE = MYISAM;


CREATE OR REPLACE VIEW order_list AS
  (SELECT
     wwoi.order_id         AS order_id,
     ac.wp_user_id         AS wp_user_id,
     wp.post_date          AS order_date,
     count(0)              AS items,
     sum(wwoim.meta_value) AS amt
   FROM
     wp_posts wp,
     wp_woocommerce_order_items wwoi,
     wp_woocommerce_order_itemmeta wwoim,
     allume_carts ac
   WHERE
     wp.ID = wwoi.order_id AND
     wwoi.order_item_id = wwoim.order_item_id AND
     wwoi.order_item_type = 'line_item' AND
     wwoim.meta_key = '_line_total' AND
     ac.id = wp.allume_cart_id AND
     ac.wp_user_id <> 0
   GROUP BY
     wwoi.order_id,
     wp.post_date,
     ac.wp_user_id);

SET SESSION group_concat_max_len = 5000;

INSERT INTO allume_client_360_temp (
  wp_user_id,
  first_name,
  last_name,
  address_1,
  address_2,
  city,
  state,
  country,
  birthday,
  occupation,
  wear_to_work,
  spend_free_time,
  where_live,
  time_of_day_text,
  social_media,
  instagram,
  pinterest,
  linkedin,
  photo,
  styling_count,
  last_styling_date,
  order_count,
  last_order_amt,
  last_order_date,
  avg_items,
  avg_amt,
  heart_count,
  comment_count,
  star_count,
  signup_date,
  utm_source,
  utm_campaign,
  utm_term,
  utm_medium,
  hear_about_allume,
  height,
  weight,
  bra_size,
  body_part_attention,
  body_part_conceal,
  fit_challenges,
  hair_complex_color,
  first_session_focus,
  looks_goal,
  pieces_focus,
  outfits_preference,
  other_goals,
  stores,
  brands,
  spending_tops,
  spending_bottoms,
  spending_dresses,
  spending_jackets,
  spending_shoes,
  style_celebs,
  style_looks,
  style_jeans,
  style_tops,
  style_dress,
  style_jacket,
  style_shoe,
  colors_preference,
  style_avoid,
  size_pants,
  size_jeans,
  size_tops,
  size_shoe,
  ears_pierced,
  jewelry_style,
  jewelry_type)
 VALUES
   (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
 ;


DROP TABLE IF EXISTS allume_client_360;

RENAME TABLE
    allume_client_360_temp TO allume_client_360;

