fields: # default is currently a copy of TJ_Maxx.yaml
    merchant_color: FORMAT
    size: LABEL
    merchant_name: PROGRAMNAME
    keywords: KEYWORDS
    currency: CURRENCY
    SKU: SKU
    product_name: NAME
    availability: INSTOCK
    product_image_url: IMAGEURL

    product_url: BUYURL # maybe?/
    buy_url: BUYURL # ??

    retail_price: RETAILPRICE
    sale_price: SALEPRICE
    long_product_description: DESCRIPTION
    primary_category: ADVERTISERCATEGORY
    shipping_price: STANDARDSHIPPINGCOST
    manufacturer_name: MANUFACTURER
    manufacturer_part_number: MANUFACTURERID

    # fields that don't seem to appear in the data
    secondary_category: N/A
    short_product_description: N/A
    product_type: N/A
    discount: N/A
    discount_type: N/A
    gender: N/A
    style: N/A
    material: N/A
    age: N/A
    brand: N/A
