# a test configuration file to figure out how to handle that all the merchants have different labels
fields:
    merchant_color: LABEL
    size: TITLE
    merchant_name: PROGRAMNAME
    keywords: KEYWORDS
    currency: CURRENCY
    SKU: SKU
    product_name: NAME
    availability: INSTOCK
    product_image_url: IMAGEURL
    product_url: BUYURL # maybe?/
    retail_price: PRICE
    sale_price: SALEPRICE
    long_product_description: DESCRIPTION
    primary_category: ADVERTISERCATEGORY
    shipping_price: STANDARDSHIPPINGCOST
    manufacturer_name: MANUFACTURER

    # fields that don't seem to appear in the data
    secondary_category: N/A
    short_product_description: N/A
    manufacturer_part_number: N/A
    product_type: N/A
    discount: N/A
    discount_type: N/A
    gender: N/A
    style: N/A
    material: N/A
    age: N/A
    brand: N/A
