# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_api', '0051_auto_20180925_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('threshold', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(default='US', max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantEditing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('product_api.merchant',),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.Merchant'),
        ),
    ]
