# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprice',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
