# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='user',
        ),
        migrations.AddField(
            model_name='rack',
            name='allume_styling_session',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.AllumeStylingSessions'),
        ),
    ]
