# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_auto_20171030_2313'),
        ('shopping_tool', '0002_auto_20171122_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('allume_styling_session', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.AllumeStylingSessions')),
            ],
        ),
        migrations.CreateModel(
            name='LookLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('layout_meta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_tool.Look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='look',
            name='look_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_tool.LookLayout'),
        ),
        migrations.AddField(
            model_name='look',
            name='products',
            field=models.ManyToManyField(through='shopping_tool.LookProduct', to='product_api.Product'),
        ),
    ]
