# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0003_auto_20171124_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='stylist',
            field=models.ForeignKey(db_column='assigned_stylist_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.WpUsers'),
        ),
    ]
