# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0004_look_stylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looklayout',
            name='layout_meta',
        ),
        migrations.AddField(
            model_name='looklayout',
            name='column_widths',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='looklayout',
            name='columns',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='looklayout',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='looklayout',
            name='row_heights',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='looklayout',
            name='rows',
            field=models.IntegerField(default=1),
        ),
    ]
