# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0006_initial_layouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
