# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_auto_20171030_2313'),
        ('shopping_tool', '0007_auto_20171125_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='products',
        ),
        migrations.AddField(
            model_name='look',
            name='look_products',
            field=models.ManyToManyField(db_column='product_id', through='shopping_tool.LookProduct', to='product_api.Product'),
        ),
        migrations.AlterField(
            model_name='look',
            name='status',
            field=models.CharField(default='Active', max_length=11),
        ),
        migrations.AlterField(
            model_name='lookproduct',
            name='look',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='shopping_tool.Look'),
        ),
    ]
