# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0010_product_is_deleted'),
        ('shopping_tool', '0008_auto_20171128_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.Product')),
                ('stylist', models.ForeignKey(db_column='assigned_stylist_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.WpUsers')),
            ],
        ),
    ]
