# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0009_userproductfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='lookproduct',
            name='cropped_dimensions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
