# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import sys

class Migration(migrations.Migration):

    if 'test' in sys.argv:
        create_table = True
    else:
        create_table = False

    dependencies = [
        ('shopping_tool', '0010_auto_20171208_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllumeWpUserStylingRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('styling_role', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'allume_wp_user_styling_roles',
                'managed': create_table,
            },
        ),
    ]
