# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0011_allumewpuserstylingroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLookFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_tool.Look')),
                ('stylist', models.ForeignKey(db_column='assigned_stylist_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.WpUsers')),
            ],
        ),
    ]
