# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0013_allumeclient360'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allumeclient360',
            options={'managed': False},
        ),
    ]
