# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0014_auto_20171212_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='look',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
