# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0015_auto_20171214_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allumeclient360',
            options={},
        ),
    ]
