# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0016_auto_20171221_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allumeclient360',
            name='wp_user_id',
        ),
        migrations.AddField(
            model_name='allumeclient360',
            name='client',
            field=models.OneToOneField(db_column='wp_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_360', to='shopping_tool.WpUsers'),
        ),
        migrations.AddField(
            model_name='allumeclient360',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
