# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0016_auto_20180105_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looklayout',
            name='layout_json',
        ),
        migrations.AddField(
            model_name='looklayout',
            name='_layout_json',
            field=models.TextField(blank=True, db_column='layout_json', null=True),
        ),
    ]
