# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0017_auto_20171221_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allumeclient360',
            options={'managed': False},
        ),
    ]
