# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0018_auto_20180111_2001'),
        ('shopping_tool', '0018_auto_20171221_1747'),
    ]

    operations = [
    ]
