# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0020_auto_20180112_2145'),
        ('shopping_tool', '0019_merge_20180115_1939'),
    ]

    operations = [
    ]
