# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0021_merge_20180116_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allumelookproducts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='allumelooks',
            options={'managed': False},
        ),
    ]
