# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0023_auto_20180116_1912'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='look',
            table='allume_looks',
        ),
    ]
