# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0025_merge_20180116_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookproduct',
            name='look',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='shopping_tool.Look'),
        ),
    ]
