# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0027_auto_20180116_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlookfavorite',
            name='look',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shopping_tool.Look'),
        ),
    ]
