# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0028_auto_20180116_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookproduct',
            options={'managed': False},
        ),
    ]
