# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0029_auto_20180116_2318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lookproduct',
            table='allume_look_products',
        ),
    ]
