# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0030_auto_20180118_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_look_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_favorites', models.IntegerField()),
                ('total_item_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('store_rank', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('look', models.ForeignKey(db_column='allume_look_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='metric_set', to='shopping_tool.Look')),
            ],
        ),
    ]
