# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import sys
from catalogue_service.settings import DEBUG


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0030_auto_20180124_0132'),
    ]

    if 'test' in sys.argv:
        operations = [
            migrations.CreateModel(
                name='AllumeUserStylistNotes',
                fields=[
                    ('id', models.BigAutoField(primary_key=True, serialize=False)),
                    ('last_author_id', models.BigIntegerField()),
                    ('user_id', models.BigIntegerField()),
                    ('notes', models.TextField()),
                    ('styling_session_id', models.BigIntegerField(blank=True, null=True)),
                    ('visible', models.IntegerField()),
                    ('date_created', models.DateTimeField()),
                    ('last_modified', models.DateTimeField()),
                ],
                options={
                    'db_table': 'allume_user_stylist_notes',
                    'managed': True,
                },
            ),
        ]
