# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0031_allumeuserstylistnotes'),
        ('shopping_tool', '0031_lookmetrics'),
    ]

    operations = [
    ]
