# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0030_auto_20180123_2210'),
        ('shopping_tool', '0032_merge_20180124_2106'),
    ]

    operations = [
    ]
