# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0032_merge_20180124_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllumeUserStylistNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('visible', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'allume_user_stylist_notes',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='allumelookproducts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='allumelooks',
            options={'managed': False},
        ),
    ]