# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 02:21
from __future__ import unicode_literals

from django.db import migrations, models


from shopping_tool.models import StyleOccasion, StyleType

def look_data(apps, schema_editor):
    StyleType.objects.create(name = "Bohemian", active = True)
    StyleType.objects.create(name = "Chic", active = True)
    StyleType.objects.create(name = "Classic", active = True)
    StyleType.objects.create(name = "Edgy", active = True)
    StyleType.objects.create(name = "Glamorous", active = True)
    StyleType.objects.create(name = "Preppy", active = True)
    StyleType.objects.create(name = "Romantic", active = True)
    StyleType.objects.create(name = "Sexy", active = True)
    StyleType.objects.create(name = "Sophisticated", active = True)
    StyleType.objects.create(name = "Sporty", active = True)

    StyleOccasion.objects.create(name = "Day Time Casual", active = True)
    StyleOccasion.objects.create(name = "Dressy Casual", active = True)
    StyleOccasion.objects.create(name = "Athleisure / Lounge", active = True)
    StyleOccasion.objects.create(name = "Business Casual", active = True)
    StyleOccasion.objects.create(name = "Business Professional", active = True)
    StyleOccasion.objects.create(name = "Vacation", active = True)
    StyleOccasion.objects.create(name = "Night Out", active = True)
    StyleOccasion.objects.create(name = "Special Event / Wedding", active = True)



class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0033_auto_20180126_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('looks', models.ManyToManyField(db_constraint=False, to='shopping_tool.Look')),
            ],
        ),
        migrations.CreateModel(
            name='StyleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('looks', models.ManyToManyField(db_constraint=False, to='shopping_tool.Look')),
            ],
        ),
        migrations.RunPython(look_data)
    ]
