# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0033_merge_20180126_2243'),
        ('shopping_tool', '0033_auto_20180126_2342'),
    ]

    operations = [
    ]
