# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0034_styleoccasion_styletype'),
        ('shopping_tool', '0030_auto_20180123_2210'),
    ]

    operations = [
    ]
