# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 00:27
from __future__ import unicode_literals

from django.db import migrations
from shopping_tool.models import LookProduct



def update_look_products_position_field(apps, schema_editor):
    lps = LookProduct.objects.filter(cropped_dimensions__isnull=False)
    for lp in lps:
    	lp.layout_position = lp.layout_position_old
    	lp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0035_merge_20180202_0027'),
    ]

    operations = [
    	migrations.RunPython(update_look_products_position_field)
    ]
