# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0036_update_look_products_position_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='stylist',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_tool.WpUsers'),
        ),
    ]
