# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0036_update_look_products_position_field'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE allume_looks ADD COLUMN position INT DEFAULT 100")
    ]
