# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 05:55
from __future__ import unicode_literals

from django.db import migrations
import sys
from catalogue_service.settings import DEBUG


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0036_update_look_products_position_field'),
    ]

    if 'test' in sys.argv or DEBUG:
        operations = [
            migrations.AlterModelOptions(
                name='lookproduct',
                options={'managed': True},
            ),
            migrations.RemoveField(
                model_name='lookproduct',
                name='layout_position',
            ),
            migrations.AlterModelOptions(
                name='lookproduct',
                options={'managed': False},
            ),
        ]
