# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 00:12
from __future__ import unicode_literals

from django.db import migrations
import sys
from catalogue_service.settings import DEBUG


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0036_update_look_products_position_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'managed': True, 'ordering': ['-updated_at']},
        ),
    ]