# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0037_rack_stylist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='styleoccasion',
            options={'verbose_name_plural': 'Style Occasions'},
        ),
        migrations.AlterModelOptions(
            name='styletype',
            options={'verbose_name_plural': 'Style Types'},
        ),
    ]
