# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import sys
from catalogue_service.settings import DEBUG


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0037_auto_20180209_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='position',
            field=models.IntegerField(default=100),
        ),
    ]