# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0037_auto_20180208_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='position',
            field=models.IntegerField(default=100),
        ),
    ]
