# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0038_auto_20180509_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='product_api.Product'),
        ),
        migrations.AlterField(
            model_name='userproductfavorite',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='product_api.Product'),
        ),
    ]
