# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 00:32
from __future__ import unicode_literals

from django.db import migrations
import sys
from catalogue_service.settings import DEBUG

class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0038_auto_20180209_0012'),
    ]

    if 'test' in sys.argv or DEBUG:
        operations = [
            migrations.AlterModelOptions(
                name='look',
                options={'managed': False, 'ordering': ['-updated_at']},
            ),
        ]
    else:
        operations = [
        ]