# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0038_auto_20180208_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'managed': False, 'ordering': ['-updated_at']},
        ),
    ]
