# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0039_auto_20180510_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('merchant_id', models.CharField(max_length=50)),
                ('stylist_id', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=50)),
                ('anna_availability', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel('WpUsers', 'WpUser'),

    ]
