# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0041_auto_20180911_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
