# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0042_auto_20180927_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stylist_id', models.BigIntegerField()),
                ('to_stylist_id', models.BigIntegerField()),
                ('old_look_snapshot', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('from_look', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='from_look', to='shopping_tool.Look')),
                ('to_look', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='to_look', to='shopping_tool.Look')),
            ],
        ),
    ]
