# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-14 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_tool', '0043_lookcopy'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shopping_tool_lookproduct"
        )
    ]
