# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20171106_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranproducts',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='primary_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
