# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171106_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranproducts',
            name='merchant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='primary_category',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='product_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='secondary_category',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
