# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_ranproducts_merchant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranproducts',
            name='merchant_name',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
    ]
