# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20171110_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=2000, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
