# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_productfeedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranproducts',
            name='modification',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
