# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20171112_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedlog',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ProductFeedLog'),
        ),
    ]
