# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_productfeedlog_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranproducts',
            name='attribute_5_color',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='attribute_6_gender',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ranproducts',
            name='attribute_8_age',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
