# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20171218_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_11',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_12',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_13',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_14',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_15',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_16',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_17',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_18',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_19',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_20',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_21',
        ),
        migrations.RemoveField(
            model_name='ranproducts',
            name='attribute_22',
        ),
    ]
