# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-14 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180102_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RanProducts',
        ),
    ]
