# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_tool', '0041_auto_20180911_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTier',
            fields=[
                ('tier', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StylistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_duty', models.BooleanField(default=False)),
                ('on_board', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('off_board_date', models.DateField(blank=True, null=True)),
                ('pay_rate', models.FloatField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_r', to='shopping_tool.WpUsers')),
                ('client_tier', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_management.ClientTier')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_r', to='shopping_tool.WpUsers')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_r', to='shopping_tool.WpUsers')),
            ],
        ),
        migrations.CreateModel(
            name='StylistRole',
            fields=[
                ('role', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='role',
            field=models.ForeignKey(default='Stylist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_management.StylistRole'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_tool.WpUsers', unique=True),
        ),
        migrations.CreateModel(
            name='StylistManagement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stylist_management.stylistprofile',),
        ),
    ]
