# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
