# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set([]),
        ),
    ]
