# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0002_auto_20171211_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
