# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0003_auto_20171214_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='autumn_precipitation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_snowfall',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_sun',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_wind',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_precipitation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_snowfall',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_sun',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_wind',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_precipitation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_snowfall',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_sun',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_wind',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_precipitation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_snowfall',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_sun',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_wind',
            field=models.FloatField(default=0),
        ),
    ]
