# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0004_auto_20171215_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='autumn_description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='autumn_icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='spring_description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='spring_icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='summer_description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='summer_icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='winter_description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='winter_icon',
        ),
    ]
