# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0005_auto_20171215_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='autumn_temperature',
            new_name='autumn_temperature_average',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='spring_temperature',
            new_name='spring_temperature_average',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='summer_temperature',
            new_name='summer_temperature_average',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='winter_temperature',
            new_name='winter_temperature_average',
        ),
    ]
