# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0006_auto_20171215_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='autumn_temperature_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='autumn_temperature_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='spring_temperature_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='spring_temperature_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='summer_temperature_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='summer_temperature_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='winter_temperature_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='winter_temperature_low',
            field=models.FloatField(default=0),
        ),
    ]
