# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0007_auto_20171215_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='autumn_temperature_average',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_temperature_high',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='autumn_temperature_low',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_temperature_average',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_temperature_high',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='spring_temperature_low',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_temperature_average',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_temperature_high',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summer_temperature_low',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_temperature_average',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_temperature_high',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winter_temperature_low',
            field=models.FloatField(default=None, null=True),
        ),
    ]
